name: main

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    permissions:
      pages: write
      

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Generate
        run: pnpm generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.todolist }}
          publish_dir: ./dist
